command.whereami.response=&aDu bist derzeit mit &e{0} &averbunden, zusammen mit &e{1} &aanderen Spielern.
forms.language.title=Sprache ändern
forms.language.description=Bitte wählen Sie Ihre bevorzugte Sprache aus.
forms.language.changed=&aDeine Sprache wurde in &e{0}&a geändert.
engine.devmode.warning=&cDieser Server läuft im DEV-Modus.
dreamland.command.server.connecting=&aVerbinde mit &e{0}&a…
dreamland.command.no-permission=&cDu hast keine Berechtigung, diesen Befehl zu verwenden.
