command.whereami.response=&aVous êtes actuellement connecté à &e{0} &aavec &e{1} &aautres joueurs.
forms.language.title=Changer de langue
forms.language.description=Veuillez sélectionner votre langue préférée.
forms.language.changed=&aVotre langue a été changée en &e{0}&a.
engine.devmode.warning=&cCe serveur fonctionne en mode DÉVELOPPEMENT.
dreamland.command.server.connecting=&aConnexion à &e{0}&a…
dreamland.command.no-permission=&cVous n’avez pas la permission d’utiliser cette commande.
