command.whereami.response=&aSei connesso su &e{0} &acon &e{1} &aaltri giocatori.
forms.language.title=Cambia la lingua
forms.language.description=Seleziona la tua lingua preferita.
forms.language.changed=&aLa tua lingua è stata modificata in &e{0}&a.
