command.whereami.response=&aJe bent momenteel verbonden met &e{0} &asamen met &e{1} &aandere spelers.
forms.language.title=Verander Language
forms.language.description=Kies alsjeblieft je voorkeurige taal.
forms.language.changed=&aJe taal is veranderd naar &e{0}&a.
engine.devmode.warning=&cDeze server draait in de ontwikkelmodus.
dreamland.command.server.connecting=&aVerbinden met &e{0}&a…
dreamland.command.no-permission=&cJe hebt geen toestemming om dit commando te gebruiken.
